### ISSUE TITLE
WiFiNINA Updater Error validating flashed firmware

### ISSUE THREAD

**Issue by sderodeff** [arduino/nina-fw#45]
Trying to update the Nina firmware on the UNO WiFi rev2  board and failing with error validating flashed firmware. I'm using IDE 1.8.12 and NINA firmware 1.3.0 for Arduino Uno WiFi Rev2 and the updater fails repeatedly after erasing the existing firmware, programming 986112 bytes with the message "Error validating flashed firmware". I've tried earlier versions of NINA as well and get same failure. Also note that during the update, I get the following message on the updater in the ide: java.lang.Exception: Error validating flashed firmware
	at cc.arduino.plugins.wifi101.flashers.java.NinaFlasher.updateFirmware(NinaFlasher.java:106)
	at cc.arduino.plugins.wifi101.UpdaterImpl$2.run(UpdaterImpl.java:214)
And during the upload of the updater to the UNO board I get the following error: avrdude: WARNING: invalid value for unused bits in fuse "fuse5", should be set to 1 according to datasheet
This behaviour is deprecated and will result in an error in future version
You probably want to use 0xcd instead of 0xc9 (double check with your datasheet first). I don't think that last bit is relevant but for completeness I included it.

I would really like to get this fixed since now the WiFi is totally broken.

**Comment by kyrsjo** [comment]
Hi,
I had the same issue, however following the advice of this thread [1] I simply tried again a few times (including unplugging/replugging the Uno Rev2, and not touching anything on the computer while it ran in case it is sensitive to timing jitter or something). Eventually it worked, and it succeeded.

[1] https://forum.arduino.cc/index.php?topic=650091.0
